# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Kevin's Blog
subtitle:
description: "ğŸ„ğŸ… Where there is a will ,<br>ğŸˆğŸ there is a way."
keywords:
author: Kevin Roy Lo
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://kevinroy.tk
root: /
permalink: posts/:title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 404.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: draft
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git
    repo: git@git.coding.net:lqyygtaps0312/zoroblog.git
    branch: master
    message: Kevin's blog.
#- type: baidu_url_submitter # ç™¾åº¦

symbols_count_time:
  symbols: true
  time: false
  total_symbols: false
  total_time: false

# algolia:
#   applicationID:
#   apiKey:
#   indexName: yearito blog
#   chunkSize: 5000

search:
  path: search.xml
  field: post # æŒ‡å®šæœç´¢èŒƒå›´ï¼Œå¯é€‰ post | page | all
  format: html # æŒ‡å®šé¡µé¢å†…å®¹å½¢å¼ï¼Œå¯é€‰ html | raw (Markdown) | excerpt | more
  limit: 10000

# Security
encrypt:
  enable: true
  default_abstract: æ­¤æ–‡ç« å·²è¢«åŠ å¯†ï¼Œéœ€è¦è¾“å…¥å¯†ç è®¿é—®ã€‚
  default_message: è¯·è¾“å…¥å¯†ç ä»¥é˜…è¯»è¿™ç¯‡ç§å¯†æ–‡ç« ã€‚

# æ–‡ç« æœ«å°¾æ·»åŠ "æœ¬æ–‡ç»“æŸ"æ ‡è®°
post_end_tag:
  enabled: true
  icon: paw

marked:
  gfm: true
  breaks: false

# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true
  # enable: false
  pluginRootPath: live2dw/ # Root path of plugin to be on the site (Relative)
  pluginJsPath: lib/ # JavaScript path related to plugin's root (Relative)
  pluginModelPath: assets/ # Relative model path related to plugin's root (Relative)
  # scriptFrom: local # Default
  scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # Your custom url
  tagMode: true # Whether only to replace live2d tag instead of inject to all pages
  log: false # Whether to show logs in console
  model:
    use: live2d-widget-model-shizuku # èŒç³»å°‘å¥³
    # use: live2d-widget-model-koharu  # æƒ…ä¾£ å¥³
    # use: live2d-widget-model-haruto  # æƒ…ä¾£ ç”·
    # use: live2d-widget-model-tororo   # å°ç™½çŒ«
    # use: live2d-widget-model-hijiki  # å°é»‘çŒ«
    # use: live2d-widget-model-wanko # npm-module package name
    # use: wanko # folder name in (hexo base dir)/live2d_models/
    # use: ./wives/wanko # folder path relative to hexo base dir
    # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # Your custom url
  display:
    position: left
    width: 100
    height: 180
  mobile:
    show: false
  react:
    opacityDefault: 0.7 # é»˜è®¤é€æ˜åº¦

douban:
  user:
  builtin: false
  book:
    title: "æˆ‘çš„ä¹¦å•"
    quote:
  movie:
    title: "æˆ‘çš„ç”µå½±"
    quote:
  game:
    title: "æˆ‘çš„æ¸¸æˆ"
    quote:
  timeout: 10000

# å›¾ç‰‡æ‡’åŠ è½½
lazyload:
  enable: false
  onlypost: true
  loadingImg: # eg /images/loading.gif

# ç™¾åº¦ä¸»åŠ¨æ¨é€
baidu_url_submit:
  count: 100 # æäº¤æœ€æ–°çš„ä¸€ä¸ªé“¾æ¥
  host: # åœ¨ç™¾åº¦ç«™é•¿å¹³å°ä¸­æ³¨å†Œçš„åŸŸå
  token: # è¯·æ³¨æ„è¿™æ˜¯æ‚¨çš„ç§˜é’¥ï¼Œæ‰€ä»¥è¯·ä¸è¦æŠŠåšå®¢æºä»£ç å‘å¸ƒåœ¨å…¬ä¼—ä»“åº“é‡Œ!
  path: baidu_urls.txt # æ–‡æœ¬æ–‡æ¡£çš„åœ°å€ï¼Œæ–°é“¾æ¥ä¼šä¿å­˜åœ¨æ­¤æ–‡æœ¬æ–‡æ¡£é‡Œ
